<?php

namespace App\Http\Controllers;
use App\Http\Controllers\Controller;


class Common extends Controller{
    public  function _initialize(){
//        parent::_initialize(); // TODO: Change the autogenerated stub
//        $conf = new ConfModel();
//        $_confres = $conf->getAllConf();
//        foreach ($_confres as $k=>$v){
//            $confres[$v['enname']]=$v['values'];
//        }
//        $this->assign('confs',$confres);

        var_dump(1);exit;
    }
}
